config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :users, only:[] do
    resources :userfiles do
      collection do
        post :plupload
      end
      member do
        get :preview
        get :download
      end
    end
  end

  resources :tags, only: [:index]
end

app/models/userfile.rb
class Userfile < ActiveRecord::Base
  # :title, :location, :user_id, :mimetype, :preview_type
  mount_uploader :location, UserfileUploader

  belongs_to :user
  has_many :userfile_tags
  has_many :tags, through: :userfile_tags

  default_scope { order('created_at DESC') }

  def random_string
    @randomstring ||= SecureRandom.hex(10)
  end

  def set_tags(tags_list)
    # Сначала удаляем отсутствующие
    self.userfile_tags.each do |tag|
      tag.destroy if !tags_list.include?(tag.tag.name)
    end

    # Добавляем отсутствующие в базе
    tags_list.each do |tag_name|
      tag = Tag.find_by_name(tag_name)
      tag = Tag.create(:name => tag_name) if tag.blank?
      self.tags << tag if !self.tags.include?(tag)
    end
  end
end

app/controllers/userfiles_controller.rb
require 'tempfile'

class UserfilesController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  before_filter :check_user_permission, except: [:index]

  before_filter :set_user
  before_filter :set_file, :only => [:edit, :update, :destroy, :preview, :download]

  before_filter :assemble_chunks, :only => [:plupload]

  def index
    if (@user.blank?)
      redirect_to root_path, notice: I18n.t('errors.absent_collection')
    else
      @files = @user.files

      @self_collection = (current_user.present? && (current_user.id.to_i == @user_id))
    end
  end

  def new
    @file = current_user.files.new
    @user = current_user
  end

  def create
    @file = Userfile.new(new_file_params)
    @file.user_id = @user_id

    if @file.save
      redirect_to user_userfiles_path(@user_id)
    else
      redirect_to new_user_userfile_path(@user_id), notice: I18n.t('errors.files.create_error')
    end
  end

  def plupload
    # Если используются чунки, коллекционируем их до получения всех частей (может быть асинхронно) - в before_filter

    @file = Userfile.new(params.permit(:location, :title))

    @file.content_type = @mime_type if @mime_type.present?
    @file.file_type = @type_detector.type.to_s if @type_detector.present?
    @file.file_size = @file_size if @file_size.present?
    @file.filename = @filename if @filename.present?
    @file.user_id = @user_id

    Rails.logger.info("DBG: Saved file = #{@file.inspect}")

    if @file.save
      if params[:tags].present?
        @tags = params[:tags].split(',')
      end
      @tags ||= Array.new

      @file.set_tags(@tags)

      Rails.logger.info("DBG: File after save = #{@file.inspect}")

      redirect_to user_userfiles_path(@user_id)
    else
      Rails.logger.info("File load errors: #{@file.errors.full_messages.join('; ')}")
      redirect_to new_user_userfile_path(@user_id), notice: I18n.t('errors.files.create_error')
    end
  end

  def edit
    @user = current_user
  end

  def update
    if params[:userfile][:tags].present?
      @tags = params[:userfile][:tags].split(',')
    end
    @tags ||= Array.new

    @file.set_tags(@tags)

    if @file.update_column(:title, params[:userfile][:title])
      redirect_to user_userfiles_path(@user_id)
    else
      redirect_to new_user_userfile_path(@user_id), notice: I18n.t('errors.files.update_error')
    end
  end

  def destroy
    @file.remove_location!
    @file.delete
    redirect_to user_userfiles_path(@user_id)
  end

  def preview
    if @file.file_type == 'image'
      redirect_to @file.location_url(:preview)
    elsif @file.file_type == 'video'
      redirect_to Settings.files.video_preview_path
    else
      redirect_to Settings.files.file_preview_path
    end
  end

  def download
    send_file @file.location.path, :disposition => "attachment", :filename => @file.filename, :length => @file.file_size
  end

  private

  def set_user
    @user_id = params[:user_id].to_i
    @user = User.find(@user_id)
  end

  def set_file
    @file_id = params[:id].to_i
    @file = Userfile.find(@file_id)
  end

  def new_file_params
    params.require(:userfile).permit(:user_id, :title, :location)
  end

  def assemble_chunks
    if (params[:chunks].present?)
      file_id = params[:name]
      chunks = chunks_get(file_id) || Array.new
      if !chunks.is_a?(Array)
        chunks = Array.new
      end

      # Отключаем финалайзер для временного файла
      ObjectSpace.undefine_finalizer(params[:file].tempfile)
      chunks[params[:chunk].to_i] = params[:file].tempfile.path

      # Проверяем собраны-ли все чунки
      chunks_count = (chunks.reject { |c| c.blank? }).count
      if chunks_count == params[:chunks].to_i
        Rails.logger.info("DBG: chunks = #{chunks.inspect}")
        chunks_set(file_id, Array.new)

        # Собираем один файл из отдельных чунков
        tmp_file = Tempfile.new('chunk')
        Rails.logger.info("DBG: result file = #{tmp_file.path}")
        chunks.each do |chunk_name|
          chunk = File.open(chunk_name)
          if tmp_file.write(chunk.read) > 0
            chunk.close
            File.unlink(chunk_name)
          end
        end

        @mime_type = FileMagic.new(FileMagic::MAGIC_MIME).file(tmp_file.path)

        location = ActionDispatch::Http::UploadedFile.new({
                                                              :filename => file_id,
                                                              :content_type => @mime_type,
                                                              :tempfile => tmp_file
                                                          })

        @filename = file_id
        @type_detector = ::FileTypeDetector.new(tmp_file.path)
        @file_size = tmp_file.size

        Rails.logger.info("DBG: filename = #{@filename}")
        Rails.logger.info("DBG: mime_type = #{@mime_type}")
        Rails.logger.info("DBG: type = #{@type_detector.type}")

        params[:location] = location
        true
      else
        chunks_set(file_id, chunks)
        render :nothing => true
        false
      end
    else
      params[:location] = params[:file]
    end
  else
    true
  end

  def chunks_set(file_id, list)
    $redis.set("chunks_#{current_user.id}_#{file_id}", list.to_json)
  end

  def chunks_get(file_id)
    json = $redis.get("chunks_#{current_user.id}_#{file_id}")
    begin
      JSON.parse(json)
    rescue
      Array.new
    end
  end
end

app/views/userfiles/edit.html.haml
%h2{:align => 'center'}
  = I18n.t('file_labels.edit_title')
.form-container
  = form_for [@user, @file], :html => { :role => 'form', :class => 'forms' } do |f|
    .form-group
      %label{ for: "title" }
        = I18n.t('file_labels.title')
      = f.text_field :title, class: 'form-control', value: @file.title
    .form-group
      %label{ for: "tags" }
        = I18n.t('file_labels.tags')
      = f.text_field :tags, class: 'form-control', value: @file.tags.pluck(:name).join(',')
    %button.btn.btn-success{ type: 'submit' }
      = I18n.t('file_labels.save')


:javascript
  $(function(){
    $( "#file_tags" ).tagit({
      allowSpaces: true,
      autocomplete: {
        delay: 0,
        minLength: 2,
        source: '/tags',
      }
    })
  });

app/views/userfiles/index.html.haml
%h2
  - if @self_collection
    = I18n.t('your_collection')
  - else
    = I18n.t('collection')
- if @self_collection
  = link_to new_user_userfile_path(@user_id) do
    %button.btn.btn-primary.btn-actions
      = I18n.t('new')
#files
  - if @files.present?
    - @files.each do |file|
      %div.image-list-container
        %a.image-list-link{"data-gallery" => "", :href => download_user_userfile_path(file, :user_id => @user_id), :title => file.title}
          %img.image-list-img{:alt => file.title, :src => preview_user_userfile_path(file, :user_id => @user_id)}/
        - if @self_collection
          %div.image-list-actions-container
            %div.image-list-actions
              = link_to edit_user_userfile_path(@user_id, file.id), :class => 'no_underline' do
                %span.glyphicon.glyphicon-edit
              = link_to user_userfile_path(@user_id, file.id), :class => 'no_underline', :method => :delete, :data => {:confirm => I18n.t("delete_sure")} do
                %span.glyphicon.glyphicon-remove

app/views/userfiles/new.html.haml
%h2{:align => 'center'}
  = I18n.t('file_labels.new_title')
#console.plupload-error
#filelist
  %table.table.table-bordered.table-hover
    %tbody{id: 'filelist_body'}
      %tr
        %th= "Имя файла"
        %th= "Размер"
        %th= "Описание"
        %th= "Тэги"
        %th= "Прогресс"
%p
  &nbsp;
#container
  %button.btn.btn-sm.btn-primary{:id => 'browse_files'}
    Выбрать файлы
  %button.btn.btn-sm.btn-danger{:id => 'uploader_stop'}
    Остановить загрузку
  %button.btn.btn-sm.btn-primary{:id => 'uploader_start'}
    Загрузить
:javascript
  $(function(){
    $("#plupload-error").hide();

    var uploader = new plupload.Uploader({
      runtimes : 'html5,flash,silverlight,html4',
      flash_swf_url : 'http://rawgithub.com/moxiecode/moxie/master/bin/flash/Moxie.cdn.swf',
      silverlight_xap_url : 'http://rawgithub.com/moxiecode/moxie/master/bin/silverlight/Moxie.cdn.xap',

      browse_button : 'browse_files',
      container: document.getElementById('container'),

      url: '#{plupload_user_userfiles_path(current_user)}',
      multipart_params: {
        '#{request_forgery_protection_token}': '#{form_authenticity_token}',
        '#{Rails.application.config.session_options[:key]}': '#{request.session_options[:id]}'
      },


      chunk_size: '100kb',
      max_retries: 5,

      filters : {
          mime_types: [
              {title : "Image files", extensions : "jpg,gif,png"},
              {title : "Video files", extensions : "avi,mpg,mpeg,mov,mkv,wmv,mp4"},
              {title : "Audio files", extensions : "wav,mp3"},
              {title : "Zip files", extensions : "zip"}
          ]
      },

      init: {
          PostInit: function() {
              $("#uploader_start").hide();
              $("#uploader_stop").hide();

              $('#uploader_start').click(function() {
                var success = true;

                for (i = 0; i < uploader.files.length; i++) {
                  file = uploader.files[i];
                  title = $("#title"+file.id).val();
                  if (title.trim() == '') {
                    success = false;
                  };
                };

                if (!success) {
                  $('#console').show();
                  $('#console').html('Заполните описание файлов!');
                } else {
                  uploader.start();
                  $("#uploader_start").hide();
                  $("#uploader_stop").show();
                  return false;
                };
              });

              $("#uploader_stop").click(function() {
                uploader.stop();
                $("#uploader_start").show();
                $("#uploader_stop").hide();
              });
          },

          FilesAdded: function(up, files) {
              $("#uploader_start").show();
              plupload.each(files, function(file) {
                document.getElementById('filelist_body').innerHTML +=
                  '<tr><td>'+file.name+ '</td><td>' + plupload.formatSize(file.size) + '</td><td><input class="form-control" width="100%" type="text" id="title'+file.id+'"/></td><td><input type="text" id="tags'+file.id+'" class="tags_inputs"></td><td id="fileprogress'+file.id+'"></td></tr>';
              });

              $(".tags_inputs").tagit({
                allowSpaces: true,
                autocomplete: {
                  delay: 0,
                  minLength: 2,
                  source: '/tags',
                }
              });
              up.disableBrowse();
              $("#browse_files").prop("disabled",true);
          },

          UploadFile: function(up, file) {
            up.settings.multipart_params['title'] = $("#title"+file.id).val();
            up.settings.multipart_params['tags'] = $("#tags"+file.id).val();
          },

          BeforeUpload: function(up, file) {
            $('#console').hide();
            $("#uploader_stop").show();
            $("#uploader_start").hide();
          },

          UploadProgress: function(up, file) {
              document.getElementById('fileprogress'+file.id).innerHTML = file.percent + "%";
          },

          Error: function(up, err) {
              $('#console').html("\nОшибка #" + err.code + ": " + err.message);
              $('#console').show();
          },

          UploadComplete: function() {
            if( uploader.total.uploaded >= uploader.files.length)
            {
              window.location = '#{user_userfiles_path(current_user)}';
            }
            $("#uploader_start").hide();
            $("#uploader_stop").hide();
          }
      }
    });

    uploader.init();
  });