config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :users, only:[] do
    resources :userfiles do
      collection do
        post :plupload
      end
      member do
        get :preview
        get :download
      end
    end
  end

  resources :tags, only: [:index]
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to I18n.t('menu.home'), root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/navigation_links_right'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %li
    = link_to I18n.t('menu.collection'), user_userfiles_path(current_user)

app/views/layouts/_navigation_links_right.html.haml
- if user_signed_in?
  %li
    = link_to I18n.t('menu.logout'), destroy_user_session_path, :method => :delete
- else
  %li
    = link_to I18n.t('menu.login'), new_user_session_path
  %li
    = link_to I18n.t('menu.signup'), new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Test Metastudio'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Test Metastudio'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield